development:
  adapter: postgresql
  encoding: utf8
  database: puzzle_development
  pool: 5
  username: postgres
  password: 1234
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: puzzle_test
  pool: 5
  username: postgres
  password: 1234
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: puzzle_production
  pool: 5
  username: postgres
  password: 1234
  host: localhost

cucumber:
  <<: *TEST
